#version: "3.8"
#
#services:
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#
#    environment:
#
#      # ========== KRaft Mode ==========
#      KAFKA_PROCESS_ROLES: "broker,controller"
#      KAFKA_NODE_ID: 1
#
#      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
#
#      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#
#      # ========== Listeners ==========
#      KAFKA_LISTENERS: >
#        PLAINTEXT://0.0.0.0:9092,
#        CONTROLLER://0.0.0.0:9093
#
#      KAFKA_ADVERTISED_LISTENERS: >
#        PLAINTEXT://localhost:9092
#
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
#        PLAINTEXT:PLAINTEXT,
#        CONTROLLER:PLAINTEXT
#
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#
#      # ========== Storage ==========
#      KAFKA_LOG_DIRS: /var/lib/kafka/data
#
#      # ========== Single Node Dev ==========
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#
#      # ========== Auto Topic ==========
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
#
#    volumes:
#      - kafka-data:/var/lib/kafka/data
#
#volumes:
#  kafka-data:

services:

  Kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: Kafka

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:

      # ========== KRaft ==========
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "XlAxznMgSEa7AjH3w8ep5g"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # ========== Listeners ==========
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ========== Storage ==========
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # ========== Single Node ==========
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # ========== Topics ==========
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # ========== Memory ==========
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
